language: java
deploy:
  provider: heroku
  api_key:
    secure: bNc0uo50qXrKjXWiMqNzEOMKc0pUVO1aAkULBiuBf7278Fqp++aOYYl4jvh93g2B9hYj47eRc7FSaf5Wi1F6nlRdOKIJ6HGbN/ZF7PNPGIMHIxQgRc0Gq5WJzRaLLDs9JxYzdvl+uR1phWhl3omOwMr6HG5sPB4V3Y2dmILshtFMjnhYcBputd5GEs4FdSHmIHCXaJ0vGEPsX1tA+cCxNNAsG3gzZINiNBI+K7tj9rMCBrNUmBJgFyn/HqKjWIXFN3isi9yKSKkYNKQGp56NEQ/HzAYHt9aHtKA12x6jFxWjxvW00auscp+qXjycafXGpeAa6+hHsmQJPwiUHgFxkHa4QaBfkQBRJODq8wyIpFcfLfWGqvVB2T1aKFRirf/Vv35U9WvXBgXyLTRBXe9KAseSPjWvF+hdhjSfgHFNIZ2TheBV7t3KL7l+ymXGCR9zZLBrHU8KO0qNfyUlgx3le/JOpmtBsxYUP0IHmBmaJPGrY2/pEEtjJSqRY3z5Tsc+/qwC54aQER801ivJ3pYiXPZ1o8Kqe4/e6dp5ZHm6qAE93dbmVjqm0yUagkVOiIjJFNp5YggvHhdkLySTwOGVXX5l/JqP7IT9M6DzN2bEI7hQ02Cc0I+kJbPzJ1qz8fbcSO4Rfy/rCGLCwD1hmEiLV31bcHrGfTk9yneDiPcBfwU=
  app: powerful-stream-98052
