language: java
deploy:
  provider: heroku
  api_key:
    secure: JKsfbN92jGjiGET5OxQjKYS8RH1eV1Bz4pzoJxEGjD2fZht0JnY7XenLnq/sE98d5xeyLRPBO3F5hMh9eTItybJeEP9XrSKx2UoxMJM7TT4L9WliXuXD7XLs5YLUmyFZ74vMZP79cGk5lVn7BnuosGQGmwqRB9TDcVhOkY59DVHSTZTha8dNQLLMdRGjyGZI1jgiqhW5rsM1514ZQLTcaW8JVegdvM9G9mRQpTbDtnmNHDYvcv71kuQn3aKkflX4NrxDFaCQfquLUxeIQglIJWNNN+DZtG2ANMVDKJVhQ7g1KCjSt/bKn4WP5MTgp0Y7wCi+MqqlUZVpUtV14yLahLl59XAFHjTT+o3/Hte//hG/b+24nsjXtdwWQ7Bn3Ee3Xf5qLC7hpzQWoG7JquKCr/EJv4YDd4/xEchmgk0V8xmanH8V7pRK6zMl5jcSKa3ZwcTygAq28uddVghLiNKf+4EXAx/re1iQcHG3emzALFZKH0fADBZA+JWF06/l23+3mGzVqyejIjgDsosUdgD53rJI5Iiysj1VOZIwoxzJYQ0RgzG53DyjDWkt3cibQUpzO8tRqFpppHlxbcFXZaJ5T8gT0LJOOyj7HAw1iqqaEv2Heimo48gmumNaX+V7K4s8pB1bkhzrbQ7xF8v4P1YR/kjXdcgCmBI/II7HxPLlJy0=
  app: powerful-stream-98052
