language: java
deploy:
  provider: heroku
  api_key:
    secure: ph+aPMtvJlSb80qlWMLa4vRv9DMV8ENW0RClgoDtkNRjfHMKgYo9oa2OOXWvO03n+fD7CahS2oxoznwQOxxxH792TWj5mzOjGkmCW2/2WzLtD+zhLtU+KbV2UBcaihsMxq2/CPJK/yq/aiUMMDNjDI5R5MAClrgiH083KxPhI6MqENSBMsI4pgDIk84qmgC6It0rFKFzxMCOAnWzqsRIXyGPThpKTvgDe4CL1QYBWFAN+Bt2X7gzeHswa8BvSMl3SKZeryFjBkJ1sDVAwH8cSjlJH/auEp0qWoDVwWnNQzrzxnYZPohgSePAQyKsR+GBLk6AZdIS8fVt95iPD07/Er1L8a4PjDrd/ErxfFA6gnfMNElii7wjKdnH0ukgXMD1tWK33Q/llafVKlx4Bkh8IJIELuItof9NLWt8CIqdB1C/NXW8vsejPQrkN9r27NzRP5uoUn6MJ9EEbgha60aTvTObEiIy9mE+JqbpGEThpmDrJvRUi5dGW0Cnq9lkz5QxPwN/I1KU4cqVUW7QL49gRQpdi84aFsgCm468F6mHDC3Iltt9KvA4UDApivLldN6kwptQNYWAs0E3GY8BzyflmOXIrAoCe1qdsvFrD4wsNsIuBUllL/Rqn/0HyKzeJ1EpsrXJ8s0umHoexvuq1D1ERSmWNhrvEFbIOpcyB2uIAMs=
  app: powerful-stream-98052
