language: java
deploy:
  provider: heroku
  api_key:
    secure: mODxHzoZuO/oCQP2Oknfv1y3t9BszCCoWrdv1QzP/+Cc6qeNGpTWHhtJZN9+yNS3IEzjSb3wFyuVVxiMuWV/nIXe87UgTfKzsbvbX/g7y83UH0fmsmXglVJlb+qVAdO47CaIdTmWliudiDwbbPMSUHP8ZZTvb/f3VPrxfFJpDQTJvgN91Ajc2XVaNvedUdJ632f4utPB49fhmIQ1XiwyHsM0EnOppYQ3cm2gnyzG+SOIqul4fuzSydAS0lqgF4UHKkNZpLQZ1Ijf78My0i/uUrL/XEgwzxGqNcjCOUcl/LYEzPZBQD0DSU4FkI/9MGPRfIfqpHSO5wCW2/E88sPn69JqxtTzsA42qFpD10TK2Q47Laucsakz6h4MijtQFnmkvaMHxy+odmPa62jcV9j5MAQTHHKHe9qiWlWaqM5VQ5McmEBbFxRhbqox8zwQQajMGOZlRc1UuBtUjDw1Ji1aFQdJyfEo8h73MFnQAhckQiMjDl3tMsQ8vJQCKV4fUPi9mkbIZqHmoC05tLWpZVmX65746A9Oikx+iEvdJYLQanhbc18z4cX6JS4aNVrTBlb1TZ67NZQRriKmdTRT6M1+nRfwdLRgKCWyH6V2Cfn/JVHAzb3xo89eGXeGNk9rvavPkA8ViCToywssZ/zJLJ+yBQluYP/X9o1BoOioG38VQdw=
  app: powerful-stream-98052
